#!/bin/bash

if [ ! $1 ] | [ ! -f $1 ]; then
    echo "./mp4parallel <input_file> [output_name]"
    exit 1
fi

if [ ! $2 ]; then
    i="${1%\.*}.mp4"
    while [ -f $OUTPUT ]; do
        i="${OUTPUT%\.*}_1.mp4"
    done
    set -- "$1" "$i"
    unset i
fi

ffmpeg -v -1 -i $1 -vn -f wav - | neroAacEnc \
    -q 0.3 -ignorelength \
    -if - \
    -of .$1.m4a
        
mkvmerge -q --no-audio -o .$1.mkv --split 4096k $1

FFOPT="-an -c:v libx264 -crf 18 -preset veryslow"

find -name ".$1-*.mkv" | parallel -S 2/root@s1.sample.com \
    -S 2/root@s2.sample.com \
    -S 2/root@s3.sample.com \
    --trc {.}.1.mkv ffmpeg -v -1 -i {} $FFOPT {.}.1.mkv
    
for f in .$1-*.1.mkv; do
    echo "file '$f'" >> .$1.txt
done
unset f

ffmpeg -v -1 -f concat -safe 0 -i .$1.txt -c copy .$1.mkv

[ -f $2 ] && mv $2 ${2%\.*}_old.${2##*\.}

if [ -f .$1.m4a ]; then
    ffmpeg -v -1 -i .$1.mkv -i .$1.m4a -c copy -movflags +faststart $2
else
    ffmpeg -v -1 -i .$1.mkv -c copy -movflags +faststart $2
fi

rm -rf .$1*
